run:
	python manage.py runserver

shell:
	python manage.py shell

migrate:
	python manage.py migrate

test:
	python manage.py test

redis:
	docker run -d -p 6379:6379 redis

superuser:
	python manage.py createsuperuser