# Generated by Django 4.1.7 on 2023-03-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='avatar',
            new_name='preview_pic',
        ),
    ]
